### ISSUE TITLE
what type of id should we use?

### ISSUE THREAD

**Issue by trigoporres** [Clitask/clitask#2]
I think exist many ways to identify a task. However, only two ways could be valid.

1. **Numbers**:  each task is assigned for one number (1,2,3,4,5,6....).
2. **Number and prefix**: each task is assigned for one number and prefix (cli-1, cli-2...).

The option 1 is more simple, this help user for identifier task. But the option 2 is more complete, add prefix help to identifier task for component. For example: home-1, university-1... The filtering of the tasks would be more powerful and the user would be able to identify his tasks in a more isolated way. However, for filter task exist the tags. 

**Conclusion:**

I think that the two options are validate, it have pros and cons. I don't know which of the two is better for the project. Or maybe there are other options that I have not contemplated.

**Comment by jlopezcur** [comment]
I prefer the first option :)
